### ISSUE TITLE
Game crashes when entering the world (VSHUD)

### ISSUE THREAD

**Issue by Craluminum2413** [Novocain1/MiscMods#2]
2.0.52 version
```
Version: v1.15.0-pre.2 (Unstable)06/06/2021 02:25:06: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at VSHUD.HackMan.SetField(Object instance, String fieldname, Object setVal)
   at VSHUD.ThreadStuff.InjectClientThread(IClientWorldAccessor world, String name, Int32 ms, ClientSystem[] systems)
   at Vintagestory.API.Common.Action.Invoke()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleLevelFinalize(_ypcV47P8X0OVDSOS28OqPTceLtG packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _jdprCcADjtIA2nbWXaiEQJt7Jmo._14ww1iwrPaPwPpAZqZCUdf3d4Sm(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._EuQCmN4cQf8FBHYrlJxd8EhIdNnA(Single )
   at _uFwaliVbJcYmzlP3dwic7HSHMr2._HlDCi3DfsJHaHE4jniBarrjFlHLB(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _EKato5MKvGk9ELCMKyl4BGVO7pe._ninJWCWaWyMG9ZSA1Eyytms1G5F(_BjQ4x8rTRChySIeXrK1HK1YSqec , String[] )
   at _btwtpE4G1MfBqD34njKFCvBcSRd._ninJWCWaWyMG9ZSA1Eyytms1G5F(ThreadStart )
```

**Comment by Novocain1** [comment]
Use the 1.15 pre compatible branch

**Comment by Craluminum2413** [comment]
I'm using 2.0.52 version

**Comment by Novocain1** [comment]
> I'm using 2.0.52 version

No, use the 2.0.6-pre.3 version.

build this branch.
https://github.com/Novocain1/MiscMods/tree/1.15-Compatible/VSHUD
this file should work https://github.com/Novocain1/MiscMods/tree/1.15-Compatible/VSHUD/mods

**Comment by Craluminum2413** [comment]
It works, thanks ![2021-06-08_02-52-38](https://user-images.githubusercontent.com/69315569/121101498-9e86f080-c804-11eb-99d1-7bbb760aba0c.png)
